---
abstract: 'A module implementing various phonetic algorithms'
author:
  - 'Maroš Kollár'
build_requires:
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Phonetic
no_index:
  directory:
    - inc
    - t
requires:
  Exporter::Lite: 0
  Text::DoubleMetaphone: 0
  Text::Metaphone: 0
  Text::Soundex: 3.00
  Text::Unidecode: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.07
