---
abstract: 'A base class for phonetic algorithms'
author:
  - 'Maroš Kollár'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Phonetic
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Text::DoubleMetaphone: 0
  Text::Metaphone: 0
requires:
  Module::Find: 0
  Moose: 0.92
  Text::Soundex: 3.03
  Text::Unidecode: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/maros/Text-Phonetic.git
version: 2.030
