--- #YAML:1.0
name:  Text-Phonetic
abstract: A module implementing various phonetic algorithms
version: 1.02
author:
  - Maroš Kollár <maros [at] k-1.com>
license:             perl
distribution_type:   module
requires:
  Text::Unidecode: 0
  Text::Soundex: 3
  Text::Metaphone: 0
  Text::DoubleMetaphone: 0
  Exporter::Lite: 0
provides:
  Text::Phonetic:
    file: lib/Text/Phonetic.pm
    version: 1.02
  Text::Phonetic::Koeln:
    file: lib/Text/Phonetic/Koeln.pm
  Text::Phonetic::DaitchMokotoff:
    file: lib/Text/Phonetic/DaitchMokotoff.pm
  Text::Phonetic::Metaphone:
    file: lib/Text/Phonetic/Metaphone.pm
  Text::Phonetic::DoubleMetaphone:
    file: lib/Text/Phonetic/DoubleMetaphone.pm
  Text::Phonetic::Soundex:
    file: lib/Text/Phonetic/Soundex.pm
  Text::Phonetic::SoundexNara:
    file: lib/Text/Phonetic/SoundexNara.pm
  Text::Phonetic::Phonix:
    file: lib/Text/Phonetic/Phonix.pm
build_requires:
  Test::Pod: 0
  Test::More: 0
  Test::Pod::Coverage: 0
urls:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
resources:
  license: http://dev.perl.org/licenses/
generated_by: created by ExtUtils::ModuleMaker 0.49
